In [ ]:



import tensorflow as tf
import matplotlib.pyplot as plt

print("Data Representation")
#=================
print("Constant Tensor")
print(tf.constant(4))

print("Array Tensor")
print(tf.constant([2,3,4]))

#==============
print("Image as a Tensor")
img = plt.imread("kitten.jpg")

img_tensor = tf.convert_to_tensor(img)
print(img_tensor)


#===========
print("Attributes of the Tensor")


print("Size")
print(img_tensor.shape)
print("DataType")
print(img_tensor.dtype)
print("nDim")
print(img_tensor.ndim)



Data Representation
Constant Tensor
tf.Tensor(4, shape=(), dtype=int32)
Array Tensor
tf.Tensor([2 3 4], shape=(3,), dtype=int32)
Image as a Tensor
tf.Tensor(
[[[124  89  67]
  [124  89  67]
  [124  89  67]
  ...
  [150 119  90]
  [150 119  90]
  [150 119  90]]

 [[125  90  68]
  [125  90  68]
  [125  90  68]
  ...
  [150 119  90]
  [150 119  90]
  [150 119  90]]

 [[127  92  70]
  [127  92  70]
  [127  92  70]
  ...
  [150 119  90]
  [150 119  90]
  [150 119  90]]

 ...

 [[114 125 121]
  [116 127 123]
  [121 132 128]
  ...
  [213  67  30]
  [214  68  31]
  [215  68  34]]

 [[105 116 112]
  [109 120 116]
  [115 126 122]
  ...
  [214  61  27]
  [216  63  29]
  [218  65  31]]

 [[100 111 107]
  [105 116 112]
  [112 123 119]
  ...
  [216  59  26]
  [218  61  28]
  [222  65  32]]], shape=(148, 215, 3), dtype=uint8)
Attributes of the Tensor
Size
(148, 215, 3)
DataType
<dtype: 'uint8'>
nDim
3
